services:
  chestra:
    build:
      context: ..
      dockerfile: Dockerfile
    image: chestra:latest
    volumes:
      - ./workflows:/workflows
      - ./plugins:/plugins
    entrypoint: ["python", "-m", "chestra"]